filter is added for additional details
TechsophyOfficial/awgment-app-account pull request #68
Opened 2023-04-12 07:18 UTC by KudumulaGangaNandini

2023-04-12 08:25 UTC, VaibhavTechsophy requested changes

2023-04-12 08:25 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/account/dto/RequestProperties.java
> +    private String context;
this is not String context

2023-04-12 08:25 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/account/service/impl/ACLServiceImpl.java
> +        requestProperties.setUserId(userFormDataSchema.getUserId());
see if you can use https://commons.apache.org/proper/commons-lang/javadocs/api-3.1/index.html?org/apache/commons/lang3/StringUtils.html

2023-04-12 08:25 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/account/service/impl/ACLServiceImpl.java
> +        requestProperties.setContext(checkACLSchema.getContext()+"");
please test before committing and pushing the code, this is a string here and a map there

2023-04-12 08:28 UTC, VaibhavTechsophy requested changes

2023-04-12 08:28 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/account/dto/ACLEntry.java
> +        ST detailTemplate = new ST(new JSONObject(this.additionalDetails).toString(), '<', '>');
'<' and '>' should not be hardcoded keep them as configurable with defaults

2023-04-12 08:28 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/account/dto/ACLEntry.java
> +        ObjectMapper mapper = new ObjectMapper();
please add test cases to test this logic of replacement

2023-04-13 11:51 UTC, VaibhavTechsophy requested changes

2023-04-13 11:53 UTC, VaibhavTechsophy requested changes

2023-04-13 11:53 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/account/dto/ACLEntry.java
> +        ST detailTemplate = new ST(new JSONObject(this.additionalDetails).toString(), '<', '>');
this is still pending

2023-04-13 12:05 UTC, KudumulaGangaNandini commented on src/main/java/com/techsophy/tsf/account/repository/document/UserFormDataDefinitionCustomRepositoryImpl.java
> +    public Optional<UserFormDataDefinition> findByUserName(String userName)
for exception purpose if with  userName data is not present

2023-04-14 10:46 UTC, VaibhavTechsophy approved these changes

2023-04-14 10:52 UTC, merged